name: CI

on:
  push:
    branches:
    - master
  pull_request:
    types:
    - opened
    - synchronize
    - reopened

jobs:
  test:
    name: ${{ matrix.os }} ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-20.04
        - ubuntu-18.04
        - ubuntu-16.04
        - macos-latest
        - windows-latest
        ruby:
        - "3.4"
        - "3.3"
        - "3.2"
        - "3.1"
        - "3.0"
        - "2.7"
        - "2.6"
        - "2.5"
        - "2.4"
        - debug
        include:
        - { os: windows-latest , ruby: mingw }
        - { os: windows-latest , ruby: mswin }
        exclude:
        - { os: windows-latest , ruby: "3.0" }
        - { os: windows-latest , ruby: debug }
        - { os: macos-latest , ruby: "2.5" }
        - { os: macos-latest , ruby: "2.4" }

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - run: bundle install --jobs 4 --retry 3

    - run: bundle exec rake

    - run: bundle exec rake build

    - run: gem install pkg/*.gem
